# -*- coding: utf-8 -*-
"""Finance Data Processing and Access Control Backend1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1AmvX2Hkj7hUHFIBMefMIXvwJr7XhFL
"""

!pip install fastapi uvicorn pydantic python-multipart

!pip install -q fastapi uvicorn nest_asyncio requests

# --- Save this as main.py in Colab ---
from fastapi import FastAPI, HTTPException, Header, Depends
from pydantic import BaseModel
from typing import List, Optional
import uuid

app = FastAPI(title="Zorvyn Finance Backend")

# --- Mock Database ---
db = {
    "users": [{"id": "admin-123", "name": "Admin User", "role": "Admin", "is_active": True}],
    "records": []
}

# --- Models ---
class User(BaseModel):
    name: str
    email: str
    role: str # Admin, Analyst, Viewer
    is_active: bool = True

class FinancialRecord(BaseModel):
    amount: float
    type: str # income, expense
    category: str
    date: str
    notes: Optional[str] = None

# --- RBAC Middleware ---
def get_user_role(x_user_id: str = Header(...)):
    user = next((u for u in db['users'] if u['id'] == x_user_id), None)
    if not user or not user['is_active']:
        raise HTTPException(status_code=401, detail="Unauthorized")
    return user['role']

# --- Routes ---
@app.post("/records", tags=["Admin"])
def create_record(record: FinancialRecord, role: str = Depends(get_user_role)):
    if role != "Admin":
        raise HTTPException(status_code=403, detail="Only Admins can create records")
    new_record = record.dict()
    new_record['id'] = str(uuid.uuid4())
    db['records'].append(new_record)
    return new_record

@app.get("/dashboard/summary", tags=["Analyst/Admin"])
def get_summary(role: str = Depends(get_user_role)):
    if role not in ["Admin", "Analyst"]:
        raise HTTPException(status_code=403, detail="Insufficient permissions")

    recs = db['records']
    income = sum(r['amount'] for r in recs if r['type'] == 'income')
    expense = sum(r['amount'] for r in recs if r['type'] == 'expense')
    return {
        "total_income": income,
        "total_expense": expense,
        "net_balance": income - expense,
        "recent_activity": recs[-5:]
    }

import uvicorn
import nest_asyncio
import asyncio

# 1. Allow nested event loops
nest_asyncio.apply()

# 2. Define a function to run the server correctly in a notebook
async def start_server():
    config = uvicorn.Config(app, host="0.0.0.0", port=8000, log_level="info")
    server = uvicorn.Server(config)
    await server.serve()

# 3. Start the server
if __name__ == "__main__":
    # In Colab, we use the existing loop instead of run()
    loop = asyncio.get_event_loop()
    loop.create_task(start_server())
    print("Server is running on http://localhost:8000")
    print("Note: In Colab, you'll need a tunnel like 'ngrok' or 'localtunnel' to access this from outside.")

!fuser -k 8000/tcp

import threading
import uvicorn
import nest_asyncio
from fastapi import FastAPI, Header, HTTPException

app = FastAPI()

@app.get("/dashboard/summary")
async def get_summary(x_user_id: str = Header(None)):
    if x_user_id != "admin-123":
        raise HTTPException(status_code=401, detail="Unauthorized")
    return {
        "total_income": 5000,
        "total_expense": 1200,
        "net_balance": 3800
    }

def run_server():
    nest_asyncio.apply()
    # Explicitly bind to 127.0.0.1
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

# Launch server in background thread
server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()
print("Server is starting on http://127.0.0.1:8000")



from google.colab import drive
drive.mount('/content/drive')

import threading, uvicorn, nest_asyncio
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware

# 1. Create the App
app = FastAPI()

# 2. ADD CORS IMMEDIATELY (Before the server starts)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3. Define your Endpoint
@app.get("/dashboard/summary")
async def get_summary(x_user_id: str = Header(None)):
    if x_user_id != "admin-123":
        raise HTTPException(status_code=401, detail="Unauthorized")
    return {
        "total_income": 5000,
        "total_expense": 1200,
        "net_balance": 3800
    }

# 4. Start the Background Server
def run_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

# Run it
threading.Thread(target=run_server, daemon=True).start()
print("✅ Backend is LIVE with CORS enabled at http://127.0.0.1:8000")

from IPython.display import HTML

# Use triple quotes (""") to wrap the entire HTML block
frontend_html = """
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 p-8">
    <div class="max-w-3xl mx-auto">
        <div class="bg-white rounded-2xl shadow-xl p-8 border border-slate-100">
            <h1 class="text-2xl font-bold text-slate-800 mb-2">Finance Dashboard</h1>
            <p class="text-slate-500 mb-8 text-sm">Zorvyn Assignment - Backend Intern</p>

            <div class="grid grid-cols-3 gap-6 mb-10">
                <div class="bg-emerald-50 p-4 rounded-xl border border-emerald-100">
                    <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wider">Total Income</p>
                    <p id="total-income" class="text-2xl font-bold text-emerald-700">$0.00</p>
                </div>
                <div class="bg-rose-50 p-4 rounded-xl border border-rose-100">
                    <p class="text-xs font-semibold text-rose-600 uppercase tracking-wider">Total Expenses</p>
                    <p id="total-expense" class="text-2xl font-bold text-rose-700">$0.00</p>
                </div>
                <div class="bg-blue-50 p-4 rounded-xl border border-blue-100">
                    <p class="text-xs font-semibold text-blue-600 uppercase tracking-wider">Net Balance</p>
                    <p id="net-balance" class="text-2xl font-bold text-blue-700">$0.00</p>
                </div>
            </div>

            <button onclick="fetchData()" class="w-full bg-slate-800 text-white font-semibold py-3 rounded-xl hover:bg-slate-900 transition shadow-lg mb-4">
                Fetch Latest Data
            </button>
            <p id="status" class="text-center text-xs text-slate-400 text-emerald-500">Ready</p>
        </div>
    </div>

    <script>
        async function fetchData() {
            const statusEl = document.getElementById('status');
            statusEl.innerText = "Syncing...";
            statusEl.className = "text-center text-xs text-slate-400";

            try {
                // FIXED URL: 127.0.0.1:8000
                const response = await fetch('http://127.0.0', {
                    headers: { 'x-user-id': 'admin-123' }
                });

                if (!response.ok) throw new Error('Auth Failed');

                const data = await response.json();

                document.getElementById('total-income').innerText = `$${data.total_income.toLocaleString()}`;
                document.getElementById('total-expense').innerText = `$${data.total_expense.toLocaleString()}`;
                document.getElementById('net-balance').innerText = `$${data.net_balance.toLocaleString()}`;

                statusEl.innerText = "Last updated: " + new Date().toLocaleTimeString();
                statusEl.className = "text-center text-xs text-emerald-500 font-bold";
            } catch (error) {
                statusEl.innerText = "Error: Make sure the Backend cell is running!";
                statusEl.className = "text-center text-xs text-rose-500 font-bold";
                console.error(error);
            }
        }
        fetchData();
    </script>
</body>
</html>
"""

# Display the HTML
display(HTML(frontend_html))

!fuser -k 8000/tcp

import threading, uvicorn, nest_asyncio, uuid, requests, time
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from IPython.display import HTML

# --- BACKEND LOGIC ---
app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# In-memory database
db = {"records": [{"id": "1", "amount": 5000, "type": "income", "category": "Salary", "date": "2024-04-01"}]}

class RecordIn(BaseModel):
    amount: float
    type: str
    category: str
    date: str

@app.get("/dashboard/summary")
async def get_summary():
    recs = db["records"]
    income = sum(r["amount"] for r in recs if r["type"] == "income")
    expense = sum(r["amount"] for r in recs if r["type"] == "expense")
    return {"total_income": income, "total_expense": expense, "net_balance": income - expense}

@app.get("/records")
async def get_records():
    return db["records"]

@app.post("/records")
async def add_record(rec: RecordIn):
    new_rec = rec.dict()
    new_rec["id"] = str(uuid.uuid4())
    db["records"].append(new_rec)
    return new_rec

# --- SERVER RUNNER ---
def start_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

threading.Thread(target=start_server, daemon=True).start()
time.sleep(2) # Give it a moment to boot

# --- FRONTEND UI (Multi-Page) ---
frontend_html = """
<script src="https://tailwindcss.com"></script>
<body class="bg-slate-50 p-6 font-sans">
    <div class="max-w-xl mx-auto bg-white rounded-xl shadow-lg p-6">
        <!-- Navigation -->
        <nav class="flex border-b mb-6 pb-2 space-x-4">
            <button onclick="showPage('dash')" class="text-slate-800 font-bold hover:text-blue-600">Dashboard</button>
            <button onclick="showPage('add')" class="text-slate-800 font-bold hover:text-blue-600">Add Entry</button>
            <button onclick="showPage('history')" class="text-slate-800 font-bold hover:text-blue-600">History</button>
        </nav>

        <!-- Dashboard Page -->
        <div id="dash" class="page">
            <h2 class="text-xl font-bold mb-4">Summary</h2>
            <div class="bg-blue-50 p-4 rounded text-center"><p class="text-sm">Net Balance</p><p id="net-val" class="text-3xl font-bold">$0</p></div>
        </div>

        <!-- Add Entry Page -->
        <div id="add" class="page hidden">
            <h2 class="text-xl font-bold mb-4">New Transaction</h2>
            <input id="amt" type="number" placeholder="Amount" class="w-full border p-2 mb-2 rounded">
            <select id="type" class="w-full border p-2 mb-2 rounded"><option value="income">Income</option><option value="expense">Expense</option></select>
            <input id="cat" type="text" placeholder="Category" class="w-full border p-2 mb-4 rounded">
            <button onclick="submitData()" class="w-full bg-blue-600 text-white py-2 rounded font-bold">Save Record</button>
        </div>

        <!-- History Page -->
        <div id="history" class="page hidden">
            <h2 class="text-xl font-bold mb-4">Transaction History</h2>
            <ul id="list" class="divide-y text-sm"></ul>
        </div>
    </div>

    <script>
        const API = "http://127.0.0.1:8000";
        function showPage(id) {
            document.querySelectorAll('.page').forEach(p => p.classList.add('hidden'));
            document.getElementById(id).classList.remove('hidden');
            if(id === 'dash') updateDash();
            if(id === 'history') updateHistory();
        }
        async function updateDash() {
            const res = await fetch(`${API}/dashboard/summary`);
            const data = await res.json();
            document.getElementById('net-val').innerText = `$${data.net_balance}`;
        }
        async function updateHistory() {
            const res = await fetch(`${API}/records`);
            const data = await res.json();
            document.getElementById('list').innerHTML = data.reverse().map(r => `<li>${r.date}: ${r.category} - $${r.amount} (${r.type})</li>`).join('');
        }
        async function submitData() {
            const payload = {
                amount: parseFloat(document.getElementById('amt').value),
                type: document.getElementById('type').value,
                category: document.getElementById('cat').value,
                date: new Date().toISOString().split('T')[0]
            };
            await fetch(`${API}/records`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(payload) });
            alert("Entry Saved!");
            showPage('dash');
        }
        updateDash(); // Initial Load
    </script>
</body>
"""
display(HTML(frontend_html))

!pip install -q fastapi uvicorn nest_asyncio

import threading, uvicorn, nest_asyncio, uuid, time, os
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from IPython.display import HTML

# --- 1. PREVENT "ADDRESS ALREADY IN USE" ---
# This kills any server running on port 8000 so you don't get errors
!fuser -k 8000/tcp

# --- 2. BACKEND ENGINE ---
app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# Mock Database
db = {"records": [{"id": "1", "amount": 5000, "type": "income", "category": "Salary", "date": "2024-04-01"}]}

class RecordIn(BaseModel):
    amount: float; type: str; category: str; date: str

@app.get("/dashboard/summary")
async def get_summary():
    recs = db["records"]
    income = sum(r["amount"] for r in recs if r["type"] == "income")
    expense = sum(r["amount"] for r in recs if r["type"] == "expense")
    return {"total_income": income, "total_expense": expense, "net_balance": income - expense}

@app.post("/records")
async def add_record(rec: RecordIn):
    new_rec = rec.dict(); new_rec["id"] = str(uuid.uuid4())
    db["records"].append(new_rec); return new_rec

# --- 3. START SERVER ---
def run_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

threading.Thread(target=run_server, daemon=True).start()
time.sleep(2) # Wait for boot

# --- 4. FRONTEND UI ---
frontend_html = """
<script src="https://tailwindcss.com"></script>
<body class="bg-slate-100 p-6 font-sans">
    <div class="max-w-md mx-auto bg-white rounded-2xl shadow-xl p-6">
        <h2 class="text-xl font-bold text-slate-800 mb-4">Zorvyn Finance Dash</h2>

        <div class="grid grid-cols-2 gap-4 mb-6 text-center">
            <div class="bg-green-50 p-3 rounded-lg"><p class="text-xs text-green-600 font-bold">INCOME</p><p id="sum-inc" class="text-xl font-bold">$0</p></div>
            <div class="bg-blue-50 p-3 rounded-lg"><p class="text-xs text-blue-600 font-bold">NET</p><p id="sum-net" class="text-xl font-bold">$0</p></div>
        </div>

        <div class="space-y-3">
            <input id="amt" type="number" placeholder="Amount" class="w-full border p-2 rounded">
            <input id="cat" type="text" placeholder="Category (e.g. Food)" class="w-full border p-2 rounded">
            <button onclick="saveData()" class="w-full bg-slate-900 text-white py-2 rounded-lg font-bold hover:bg-black">Add Record</button>
        </div>
    </div>

    <script>
        const API = "http://127.0.0.1:8000";
        async function updateUI() {
            const res = await fetch(`${API}/dashboard/summary`);
            const data = await res.json();
            document.getElementById('sum-inc').innerText = '$' + data.total_income;
            document.getElementById('sum-net').innerText = '$' + data.net_balance;
        }
        async function saveData() {
            const payload = {
                amount: parseFloat(document.getElementById('amt').value),
                type: 'income', category: document.getElementById('cat').value, date: '2024-04-02'
            };
            await fetch(`${API}/records`, {
                method: 'POST', headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(payload)
            });
            updateUI();
            document.getElementById('amt').value = '';
            document.getElementById('cat').value = '';
        }
        updateUI();
    </script>
</body>
"""
display(HTML(frontend_html))