# -*- coding: utf-8 -*-
"""Anchal_Patel_Zorvyn_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11J959SNpTKET8Q2MI5sA70eQ1roF1mIS

markdown
# Finance Data Processing Backend
**Name:** Anchal Patel  
**Email:** anchal6392patel@gmail.com  
**Role:** Backend Developer Intern Assignment
"""

# Install the web server tools


import threading, uvicorn, nest_asyncio, uuid, time
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from IPython.display import HTML

# --- 1. SETUP ---
!fuser -k 8000/tcp # Kills old servers to prevent errors
app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# Mock Database
db = {"records": [{"id": "1", "amount": 5000.0, "type": "income", "category": "Salary", "date": "2026-04-01"}]}

class RecordIn(BaseModel):
    amount: float; type: str; category: str; date: str

# --- 2. BACKEND ENDPOINTS ---
@app.get("/dashboard/summary")
async def get_summary():
    recs = db["records"]
    income = sum(r["amount"] for r in recs if r["type"] == "income")
    expense = sum(r["amount"] for r in recs if r["type"] == "expense")
    return {"total_income": income, "total_expense": expense, "net_balance": income - expense}

@app.post("/records")
async def add_record(rec: RecordIn):
    new_rec = rec.dict()
    new_rec["id"] = str(uuid.uuid4())
    db["records"].append(new_rec)
    return new_rec

# --- 3. SERVER RUNNER ---
def run_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

threading.Thread(target=run_server, daemon=True).start()
time.sleep(2) # Boot time

# --- 4. FRONTEND UI ---
frontend_html = """
<script src="https://tailwindcss.com"></script>
<div class="max-w-md mx-auto mt-10 bg-white p-8 rounded-2xl shadow-2xl font-sans border border-slate-200">
    <h2 class="text-2xl font-bold text-slate-800 mb-6">Finance Dashboard</h2>
    <div class="grid grid-cols-2 gap-4 mb-8">
        <div class="bg-emerald-50 p-4 rounded-xl border border-emerald-100">
            <p class="text-[10px] font-bold text-emerald-600 uppercase">Income</p>
            <p id="sum-inc" class="text-xl font-bold text-emerald-700">$0</p>
        </div>
        <div class="bg-blue-50 p-4 rounded-xl border border-blue-100">
            <p class="text-[10px] font-bold text-blue-600 uppercase">Net Balance</p>
            <p id="sum-net" class="text-xl font-bold text-blue-700">$0</p>
        </div>
    </div>
    <div class="space-y-4">
        <input id="amt" type="number" placeholder="Amount (e.g. 500)" class="w-full border border-slate-200 p-3 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none">
        <input id="cat" type="text" placeholder="Category (e.g. Food)" class="w-full border border-slate-200 p-3 rounded-lg">
        <button onclick="saveData()" class="w-full bg-slate-900 text-white py-3 rounded-lg font-bold hover:bg-black transition-all">Add Record</button>
    </div>
</div>
<script>
    const API = "http://127.0.0.1:8000";
    async function updateUI() {
        const res = await fetch(`${API}/dashboard/summary`);
        const data = await res.json();
        document.getElementById('sum-inc').innerText = '$' + data.total_income;
        document.getElementById('sum-net').innerText = '$' + data.net_balance;
    }
    async function saveData() {
        const payload = {
            amount: parseFloat(document.getElementById('amt').value),
            type: 'income', category: document.getElementById('cat').value, date: new Date().toISOString().split('T')[0]
        };
        await fetch(`${API}/records`, {
            method: 'POST', headers: {'Content-Type': 'application/json'},
            body: JSON.stringify(payload)
        });
        updateUI();
        document.getElementById('amt').value = '';
        document.getElementById('cat').value = '';
    }
    updateUI();
</script>
"""
display(HTML(frontend_html))

# 1. Install dependencies
!pip install -q fastapi uvicorn nest_asyncio

import threading, uvicorn, nest_asyncio, uuid
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from IPython.display import HTML

# --- BACKEND ---
app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_headers=["*"])

# Mock Database
db = {"records": [{"id": "1", "amount": 5000, "type": "income", "category": "Salary", "date": "2024-04-01"}]}

class RecordIn(BaseModel):
    amount: float; type: str; category: str; date: str

@app.get("/dashboard/summary")
async def get_summary(x_user_id: str = Header("admin-123")):
    recs = db["records"]
    income = sum(r["amount"] for r in recs if r["type"] == "income")
    expense = sum(r["amount"] for r in recs if r["type"] == "expense")
    return {"total_income": income, "total_expense": expense, "net_balance": income - expense}

@app.post("/records")
async def add_record(rec: RecordIn):
    new_rec = rec.dict(); new_rec["id"] = str(uuid.uuid4())
    db["records"].append(new_rec); return new_rec

# --- RUNNER ---
def run_server():
    nest_asyncio.apply()
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

threading.Thread(target=run_server, daemon=True).start()

# --- FRONTEND ---
frontend_html = """
<script src="https://tailwindcss.com"></script>
<div class="p-6 max-w-lg mx-auto bg-white rounded-xl shadow-md font-sans">
    <h1 class="text-2xl font-bold mb-4">Finance Dashboard</h1>
    <div class="grid grid-cols-2 gap-4 mb-6">
        <div class="bg-green-100 p-3 rounded">Income: <b id="inc">$0</b></div>
        <div class="bg-blue-100 p-3 rounded">Net: <b id="net">$0</b></div>
    </div>
    <input id="amt" type="number" placeholder="Amount" class="border p-2 w-full mb-2">
    <button onclick="save()" class="w-full bg-black text-white p-2 rounded">Add Record</button>
</div>
<script>
    async function refresh() {
        const res = await fetch('http://127.0.0');
        const data = await res.json();
        document.getElementById('inc').innerText = '$' + data.total_income;
        document.getElementById('net').innerText = '$' + data.net_balance;
    }
    async function save() {
        await fetch('http://127.0.0', {
            method: 'POST', headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({amount: document.getElementById('amt').value, type: 'income', category: 'General', date: '2024-04-02'})
        });
        refresh();
    }
    refresh();
</script>
"""
display(HTML(frontend_html))

import uuid
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional

# 1. Initialize FastAPI
app = FastAPI(title="Zorvyn Finance Backend")

# 2. Add CORS Middleware (Essential for connecting your Frontend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3. In-Memory Database (For demo purposes)
db = {
    "users": [
        {"id": "admin-123", "role": "Admin", "name": "Anchal Patel"},
        {"id": "view-456", "role": "Viewer", "name": "Guest User"}
    ],
    "records": [
        {"id": "1", "amount": 5000.0, "type": "income", "category": "Salary", "date": "2024-04-01", "description": "Initial Balance"}
    ]
}

# 4. Data Models
class RecordIn(BaseModel):
    amount: float
    type: str  # 'income' or 'expense'
    category: str
    date: str
    description: Optional[str] = "No description"

# 5. API Endpoints

# --- Dashboard Summary ---
@app.get("/dashboard/summary")
async def get_summary(x_user_id: str = Header(None)):
    # Simple Role Check
    user = next((u for u in db["users"] if u["id"] == x_user_id), None)
    if not user:
        raise HTTPException(status_code=401, detail="Invalid User ID")

    recs = db["records"]
    income = sum(r["amount"] for r in recs if r["type"] == "income")
    expense = sum(r["amount"] for r in recs if r["type"] == "expense")

    return {
        "user_name": user["name"],
        "role": user["role"],
        "total_income": income,
        "total_expense": expense,
        "net_balance": income - expense,
        "record_count": len(recs)
    }

# --- Create New Record (Admin Only) ---
@app.post("/records")
async def add_record(rec: RecordIn, x_user_id: str = Header(None)):
    user = next((u for u in db["users"] if u["id"] == x_user_id), None)

    # Requirement #4: Access Control
    if not user or user["role"] != "Admin":
        raise HTTPException(status_code=403, detail="Only Admins can create records")

    new_rec = rec.dict()
    new_rec["id"] = str(uuid.uuid4())
    db["records"].append(new_rec)
    return {"message": "Record added successfully", "data": new_rec}

# --- Get All Records ---
@app.get("/records")
async def get_all_records():
    return db["records"]

# 6. Run instruction (For local testing only)
# Run with: uvicorn main:app --reload
